name: bluemath-deep
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - xarray
  - netcdf4
  - scipy
  - scikit-learn
  - matplotlib
  - qt
  - pyqt
  - plotly
  - cartopy
  - pytest
  - cdsapi
  - keras
  - tensorflow
  # PIP packages can be added below (avoid this whenever possible)
  - pip:
      - minisom
