name: bluemath
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - xarray
  - scikit-learn
  - matplotlib
  - qt
  - pyqt
  - plotly
  - cartopy
  - pytest
  - cdsapi
  # PIP packages can be added belos (Avoid this)
  # - pip
  # - pip:
  #   - some-package
