site_name: BlueMath {Toolkit}

nav:
  - Home: index.md
  - MDA: mda.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table
            show_source: false

markdown_extensions:
  - admonition
  - codehilite

theme:
  name: "material"
