site_name: BlueMath {Toolkit}

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: table

markdown_extensions:
  - admonition
  - codehilite

theme:
  name: "material"
