name: Python Tests on Merge/Push to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
      - review_requested

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.12" # specify your required Python version

      - name: Create conda environment
        run: conda env create -f environment.yml

      - name: Run tests
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate bluemath
          python -m unittest discover tests/datamining/
