name: Python Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

jobs:
  python-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      
      - name: Create conda environment
        run: conda create -n bluemath-tk python=${{ matrix.python-version }}

      - name: Run tests
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate bluemath-tk
          python --version
          python -m unittest discover tests/datamining/
          python -m unittest discover tests/downloaders/
          python -m unittest discover tests/interpolation/
          python -m unittest discover tests/predictor/
          python -m unittest discover tests/wrappers/
